config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :programs
  resources :nutritions do 
    get :export_nutritions
    collection do 
      post :import 
    end
  end
  resources :homes
  resources :attendances
  resources :scores do
    get :export_scores
    collection do
      post :import 
    end
  end
  resources :schools
  resources :establishments do 
    collection { post :import }
  end
  resources :health_cares
  resources :students do 
    get :export
    collection { post :import }
  end
  resources :guardians
  resources :visitors
  devise_for :users
  resources :users
  root :to => 'public#index'
	get '/home', :to => 'homes#banner'
	get '/reports', :to => 'reports#index'
	
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_one :guardian, dependent: :destroy
	has_one :health_care, dependent: :destroy
	accepts_nested_attributes_for :guardian
  belongs_to :school
	has_many :scores, dependent: :destroy
	has_many :activities, through: :assistances
	has_many :nutritions, dependent: :destroy
	has_many :assistances, dependent: :destroy
	
	mount_uploader :pic, PicUploader
  
  validates :name, :gender, :last_course, :identification, :born, presence: true
  validates :last_course, numericality: { only_integer: true, less_than: 12 }
  validates :identification, numericality: { only_integer: true, less_than: 1500000000 }
  validates :id_type, inclusion: {in: %w(TI RC NUIP Otro)}
	
	def self.genderize(g)
	   joins(:nutritions, :school).where("students.gender = :gen AND schools.created_at <= :end_date", {gen: g, end_date: Time.now.midnight}) if g.present?
	end
	
	def self.dynamic(r,d,c)
		if r.present? && d.present? && c.present?
	    joins(:nutritions, :school).where("students.residency_state = :res AND students.school_id = :school_id AND students.last_course = :course", {res: r, school_id: d, course: c})
		end
	end
	
	def self.created_before(time)
	    joins(:nutritions, :school).where("schools.created_at < ?", time) if time.present?
	 end
  
  def the_school
    self.school.present? ? self.school.name : "Sin escuela"
  end
	
	def average
		adding = 0
		self.scores.each do |score| 
			adding += 1
			total += score.to_f
		end
		total = total/(adding > 0 ? adding : 1)
	end
	
	def touchdown
		self.average > 3.0 ? true : false
	end
	
  # def age
  #   now = Time.now.utc.to_date
  #   now.year - self.born.year - (self.born.to_date.change(:year => now.year) > now ? 1 : 0)
  # end
  
  def age
    now = Time.now.utc.to_date
    now.year - self.born.year - ((now.month > self.born.month || (now.month == self.born.month && now.day >= self.born.day)) ? 0 : 1)
  end
	
	def age_month
		now = Time.now.utc.to_date

    if now.month == self.born.month
      if now.day >= self.born.day then 0 else 11 end 
    elsif now.month > self.born.month
      now.month - self.born.month
    elsif now.month < self.born.month
      12 - (self.born.month - now.month)
    end
    
	end
	
	def age_medium
		if age_month >= 6
			math = 5
		else
			math = 0
		end
		response = ("#{age}.#{math}").to_f
	end
	
	def average
		@i = 0;
		@mas = 0;
    self.scores.each do |score| 
	     if score.year.to_i == Time.now.year || score.year.to_i == Time.now.year-1 
				 @i = @i + 1
			   @mas = @mas+score.score.to_f 
			  end 
     end
		@mas = @mas/@i unless @i == 0 
		return @mas
	end
	
	def lost_year
		@response = true
		 self.scores.each do |score|
			 if score.period.to_i == 5 && score.pass == true 
				 p score.period.to_i
				 p score.pass
				 @response = true
			 else
				 @response = false
			 end
		 end
		 @response
	end
  
  def self.to_csv
    attributes = ["Identificacion", "Nombre", "Tipo de identificacion", "Genero", "Direccion", "Ultimo curso", "desescolarizado", "Nacimiento", "Etnia", "Barrio", "Nacido en", "Desplazado", "Retiro", "Graduado", "Lugar de residencia", "Estrato"]
    (CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |student|
        # csv << attributes.map{ |attr| user.send(attr) }
         csv << [student.identification, student.name, student.id_type, student.gender, student.address, student.last_course, student.outschool_years, student.born, student.etnic, student.villa, student.born_state, student.displaced, student.drop, student.graduated, student.residency_state, student.zone]
      end
    end).encode('WINDOWS-1252', :undef => :replace, :replace => '')
  end
	
  # import CSV
  def self.import(file, school)
		# allowed_attributes = ["name",	"id_type",	"gender",	"address",	"last_course",	"outschool_years",	"identification",	"born",	"etnic",	"villa",	"born_state",	"displaced",	"residency_state",	"zone"]
		school = School.find(school)
		import = ImportUserCSV.new(file: file) do
		  model school.students
		end
		import.valid_header? # => false
		import.run!
		import.report.status # => :aborted
		return import.report # => "The following columns are required: "email""
		
			#     CSV.foreach(file.path, headers: true, :encoding => 'WINDOWS-1252') do |row|
			#       student = find_by_identification(row["identification"]) || new
			#       student.attributes = row.to_hash.select { |k,v| allowed_attributes.include? k }
			# student.school_id = school
			# student.save!
			#     end
  end
end

class ImportUserCSV
  include CSVImporter

  model Student
	column :email, as: [/e.?mail/i, "Correo"], to: ->(email) { email.downcase }
	column :name, as: ["Nombre"], to: ->(name) { name.downcase }
	column :id_type, as: ["Tipo de identificacion"]
	column :gender, as: ["Genero"], to: ->(gender) { gender.downcase }
	column :address, as: ["Direccion", /Direcci(ó|o)n/i ]
	column :last_course, as: ["Ultimo curso"]
	column :outschool_years, as: ["desescolarizado"]
	column :identification, as: ["Identificacion"]
	column :born, as: ["Nacimiento"]
	column :etnic, as: ["Etnia"]
	column :villa, as: ["Barrio"]
	column :born_state, as: ["Nacido en", "Ciudad de nacimiento"]
	column :displaced, as: ["Desplazado"]
	column :graduated, as: ["Graduado"]
	column :drop, as: ["Retiro", "Abandono"]
	column :residency_state, as: ["Lugar de residencia"]
	column :zone, as: ["Estrato"]
	identifier :identification
  when_invalid :abort
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :admin_only, only: [:edit, :update, :new, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    respond_to do |format|
        format.html
        format.csv { send_data @students.to_csv }
      end
  end

  # GET /students/1
  # GET /students/1.json
  def show
		@guardian = @student.guardian || Guardian.new
		@health_care = @student.health_care || HealthCare.new
    @schools = School.all
		@activities = Activity.joins(:students).where(students: {id: @student.id})
		@programs_edu =	Program.includes(:activities).where(line: "epc").joins(:activities).where(activities: {id: @activities})
		@programs_m =	Program.includes(:activities).where(line: "n").joins(:activities).where(activities: {id: @activities})
		@programs_h =	Program.includes(:activities).where(line: "h").joins(:activities).where(activities: {id: @activities})
  end
  
  def export
    @school_id = params[:student_id]
    @students = Student.where(school_id: @school_id)
    respond_to do |format|
        format.html
        format.csv { send_data @students.to_csv }
    end
  end

  # GET /students/new
  def new
    @student = Student.new
	  @student.build_guardian
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'El estudiante fue actualizado.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url, notice: 'El estudiante fue borrado.' }
      format.json { head :no_content }
    end
  end
	
  def import
  
    begin 
      @importar = Student.import(params[:file],params[:school_id])

      if @importar.status == :done
        redirect_to school_url(params[:school_id]), notice: @importar.message
      else
        redirect_to school_url(params[:school_id]), alert: "Error linea #{@importar.invalid_rows.first.line}: #{@importar.invalid_rows.first.model.errors.full_messages.join("|")}"
      end
    rescue => exception
      redirect_to school_url(params[:school_id]), alert: "#{exception.class}: #{exception.message}"
    end
  end
	

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.includes(:scores, :nutritions).find(params[:id])
    end
    
    def admin_only
      unless current_user.admin?
        redirect_to "/", :alert => "Accesso denegado."
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :id_type, :gender, :address, :last_course, :outschool_years, :identification, :born, :etnic, :villa, :born_state, :displaced, :disability, :drop, :pic, :graduated, :why, :residency_state, :zone, :guardian_id, :school_id, :health_care_id, guardian_attributes: [:id_type, :identification, :name, :last_name, :second_name, :gender, :born, :address, :villa, :zone, :department, :municipality, :phone, :cel, :email, :relationship, :student_id])
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<div class="row">
	<div class="large-12 columns"><%= simple_form_for(@student) do |f| %>
		  <%= f.error_notification %>
		  	
						<div class="row">
						  <div class="small-5 columns">
						    <%= f.label :name, class: 'inline-label inline left' do %>
								<%= fa_icon "info ls-icon" %> Nombre
							<% end %>
						  </div>
						  <div class="small-7 columns">
						    <%= f.input_field :name %>
						  </div>
						</div>
						<div class="row">
						  <div class="small-5 columns">
						    <%= f.label :pic, class: 'inline-label inline left' do %>
								<%= fa_icon "image ls-icon" %> Imagen
							<% end %>
						  </div>
						  <div class="small-7 columns">
						    <%= f.input_field :pic %>
								<% if @student.pic_url.present? %>
									<%= image_tag @student.pic_url(:thumb) %>
								<% end %>
						  </div>
						</div>
						<div class="row">
						  <div class="small-5 columns">
						    <%= f.label :id_type, class: 'inline-label inline left' do %>
								<%= fa_icon "credit-card ls-icon" %> Tipo de identificación
							<% end %>
						  </div>
						  <div class="small-7 columns">
						    <%= f.select :id_type, GeneralInfo.kids_id, prompt: "Escoger uno" %>
						  </div>
						</div>
		  	    
						<div class="row">
						  <div class="small-5 columns">
						    <%= f.label :identification, class: 'inline-label inline left' do %>
								<%= fa_icon "hashtag ls-icon" %> Identificación
							<% end %>
						  </div>
						  <div class="small-7 columns">
						    <%= f.input_field :identification %>
						  </div>
						</div>
				
						<div class="row">
						  <div class="small-5 columns">
						    <%= f.label :gender, class: 'inline-label inline left' do %>
								<%= fa_icon "venus-mars ls-icon" %> Genero
							<% end %>
						  </div>
						  <div class="small-7 columns">
						    <%= f.select :gender, GeneralInfo.gender, prompt: "Escoger un genero" %>
						  </div>
						</div>
				
		    <div class="row">
						  <div class="small-5 columns">
						    <%= f.label :last_course, class: 'inline-label inline left' do %>
								<%= fa_icon "graduation-cap ls-icon" %> Ultimo año cursado
							<% end %>
						  </div>
						  <div class="small-7 columns">
						    <%= f.input_field :last_course %>
						  </div>
						</div>
				
						<div class="row">
						  <div class="small-5 columns">
						    <%= f.label :outschool_years, class: 'inline-label inline left' do %>
								<%= fa_icon "thumbs-o-down ls-icon" %> Años desescolarizado
							<% end %>
						  </div>
						  <div class="small-7 columns">
						    <%= f.input_field :outschool_years %>
						  </div>
						</div>
		  	    
						<div class="row">
						  <div class="small-5 columns">
						    <%= f.label :born, class: 'inline-label inline left' do %>
								<%= fa_icon "child ls-icon" %> Fecha de nacimiento
							<% end %>
						  </div>
						  <div class="small-7 columns">
						    <div class="inline-select"><%= f.input_field :born, start_year: 1990 %></div>
						  </div>
						</div>
				
						<div class="row">
						  <div class="small-5 columns">
						    <%= f.label :etnic, class: 'inline-label inline left' do %>
								<%= fa_icon "group ls-icon" %> Grupo etnico
							<% end %>
						  </div>
						  <div class="small-7 columns">
						    <div class="inline-select"><%= f.input_field :etnic %></div>
						  </div>
						</div>
				
						<div class="row">
						  <div class="small-5 columns">
						    <%= f.label :born_state, required: true, class: 'inline-label inline left' do %>
								<%= fa_icon "globe ls-icon" %> Ciudad de nacimiento
							<% end %>
						  </div>
						  <div class="small-7 columns">
						    <div><%= f.select :born_state, GeneralInfo.cities, as: :grouped_select, group_method: :last, prompt: "Escoge una"  %></div>
						  </div>
						</div>
				
						<div class="row">
						  <div class="small-5 columns">
						    <%= f.label :residency_state, required: true, class: 'inline-label inline left' do %>
								<%= fa_icon "map-signs ls-icon" %> Ciudad de Residencia
							<% end %>
						  </div>
						  <div class="small-7 columns">
						    <div><%= f.select :residency_state, GeneralInfo.cities, as: :grouped_select, group_method: :last, prompt: "Escoge una"  %></div>
						  </div>
						</div>
				
		    <div class="row">
						  <div class="small-5 columns">
						    <%= f.label :villa, class: 'inline-label inline left' do %>
								<%= fa_icon "map-marker ls-icon" %> Barrio o Vereda
							<% end %>
						  </div>
						  <div class="small-7 columns">
						    <div class="inline-select"><%= f.input_field :villa  %></div>
						  </div>
						</div>
				
						<div class="row">
						  <div class="small-5 columns">
						    <%= f.label :address, class: 'inline-label inline left' do %>
								<%= fa_icon "compass ls-icon" %> Dirección
							<% end %>
						  </div>
						  <div class="small-7 columns">
						    <div ><%= f.input_field :address  %></div>
						  </div>
						</div>
				
						<div class="row">
						  <div class="small-5 columns">
						    <%= f.label :zone, class: 'inline-label inline left' do %>
								<%= fa_icon "map ls-icon" %> Estrato
							<% end %>
						  </div>
						  <div class="small-7 columns">
						    <div><%= f.select :zone, GeneralInfo.estrato, prompt: "Escoger un estrato" %></div>
						  </div>
						</div>
		  	   
		    <div class="row">
						  <div class="small-5 columns">
						    <%= f.label :displaced, class: 'inline-label inline left' do %>
								<%= fa_icon "warning ls-icon" %> Desplazado
							<% end %>
						  </div>
						  <div class="small-7 columns">
						    <div><%= f.input_field :displaced, as: :boolean  %></div>
						  </div>
			</div>
		  	
		  	<div class="row">
			<div class="small-5 columns">
				<%= f.label :drop, class: 'inline-label inline left' do %>
				<%= fa_icon "user-times ls-icon" %> Retirado
				<% end %>
			</div>
			<div class="small-7 columns">
				<%= f.input_field :drop, as: :boolean  %>
		  </div>
		</div>
		
		<div class="row">
			<div class="small-5 columns">
				<%= f.label :why, class: 'inline-label inline left' do %>
				<%= fa_icon "history ls-icon" %> Explicaciones adicionales
				<% end %>
			</div>
			<div class="small-7 columns">
				<div class="inline-select"><%= f.text_area :why  %></div>
			</div>
		</div>
		
		<div class="row">
			<div class="small-5 columns">
				<%= f.label :graduated, class: 'inline-label inline left' do %>
				<%= fa_icon "graduation-cap ls-icon" %> Graduado
				<% end %>
			</div>
			<div class="small-7 columns">
				<%= f.input_field :graduated, as: :boolean  %>
		  </div>
		</div>
		  	    
		</div>
		  	
		  <div class="form-actions text-right">
		    <%= f.button :submit, "Guardar estudiante", class: "button large success" %>
		  </div>
		<% end %></div>
</div>

app/views/students/edit.html.erb
<div class="breadcrumb">
  <h4 class="whitetxt">Editando <%= @student.name %></h4>
</div>
<div class="search-field"></div>
<div class="back_link">
  <%= link_to visitors_path do %>
    <%= fa_icon "arrow-left" %> <span class="italic">Regresar</span>
  <% end %>
</div>
<br />	


<%= render 'form' %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Id type</th>
      <th>Gender</th>
      <th>Address</th>
      <th>Last course</th>
      <th>Outschool years</th>
      <th>Identification</th>
      <th>Born</th>
      <th>Etnic</th>
      <th>Villa</th>
      <th>Born state</th>
      <th>Displaced</th>
      <th>Residency state</th>
      <th>Zone</th>
      <th>Guardian</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.id_type %></td>
        <td><%= student.gender %></td>
        <td><%= student.address %></td>
        <td><%= student.last_course %></td>
        <td><%= student.outschool_years %></td>
        <td><%= student.identification %></td>
        <td><%= student.born %></td>
        <td><%= student.etnic %></td>
        <td><%= student.villa %></td>
        <td><%= student.born_state %></td>
        <td><%= student.displaced %></td>
        <td><%= student.residency_state %></td>
        <td><%= student.zone %></td>
        <td><%= student.guardian %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>