config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :programs
  resources :nutritions do 
    get :export_nutritions
    collection do 
      post :import 
    end
  end
  resources :homes
  resources :attendances
  resources :scores do
    get :export_scores
    collection do
      post :import 
    end
  end
  resources :schools
  resources :establishments do 
    collection { post :import }
  end
  resources :health_cares
  resources :students do 
    get :export
    collection { post :import }
  end
  resources :guardians
  resources :visitors
  devise_for :users
  resources :users
  root :to => 'public#index'
	get '/home', :to => 'homes#banner'
	get '/reports', :to => 'reports#index'
	
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :student
	belongs_to :user
  validates :score, :user_id, :area, :year, :student_id, :period, presence: true
  
  
  # export CSV
  def self.to_csv
    attributes = %w{identification period area score year}
    (CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |score|
        # csv << attributes.map{ |attr| user.send(attr) }
        csv << [score.student.identification, score.period, score.area, score.score, score.year]
      end
    end).encode('WINDOWS-1252', :undef => :replace, :replace => '')
  end
  
  # import CSV
  def self.import(file, school, year, period, user)
		data = CSV.read(file.path, headers: true, :encoding => 'WINDOWS-1252') 

		data.each do |row|
  			student = Student.find_by_identification(row["identification"])
        areas = ["Naturales", "Sociales", "Lenguaje", "Matematicas", "Disciplina"]
        posible = row.to_hash.select { |k,v| areas.include? k }
  			if student.present? && student.try(:school_id).to_i == school.to_i
          scores = where(period: period).joins(:student).merge(Student.where(:identification => row["identification"]))
          if !scores.empty?
            # go trough all of them and compare with posible areas update or create
            scores.each do |score| 
              if areas.include? score.area
                score.area = score.area
                score.score = posible[score.area]
                score.student_id = student.id
                score.user_id = user
                score.period = period
                score.year = year
                score.save!
              end
            end
          else
            posible.each do |k,v|
              if v.present?
                new_score = new
                new_score.area = k 
                new_score.score = v
                new_score.student_id = student.id
                new_score.user_id = user
                new_score.period = period
                new_score.year = year
                new_score.save!
              end 
            end
          end
  			end
  		end
      # "the end"
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end
  
  def export_scores
    @school_id = params[:score_id]
    @students = Student.where(school_id: @school_id)
    @ids = []
    @students.each do |student|
      @ids.push(student.id)
    end
    @scores = Score.where(student_id: @ids)
    respond_to do |format|
        format.html
        format.csv { send_data @scores.to_csv }
    end
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
	
  def import
    begin
      Score.import(params[:file],params[:school_id],params[:date][:year], params[:period],params[:user_id])
      redirect_to school_url(params[:school_id]), notice: "Notas importadas."
    rescue => exception
      redirect_to school_url(params[:school_id]), alert: "#{exception.class}: #{exception.message}"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:identification, :period, :area, :score, :year, :pass, :student_id, :user_id)
    end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= simple_form_for(@score) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :identification %>
    <%= f.input :period %>
    <%= f.input :area %>
    <%= f.input :score %>
    <%= f.association :student %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Scores</h1>

<table>
  <thead>
    <tr>
      <th>Identification</th>
      <th>Period</th>
      <th>Area</th>
      <th>Score</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= score.identification %></td>
        <td><%= score.period %></td>
        <td><%= score.area %></td>
        <td><%= score.score %></td>
        <td><%= score.student.present? ? score.student.identification : 'no hay estudiante' %></td>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>

app/views/scores/new.html.erb
<h1>New Score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identification:</strong>
  <%= @score.identification %>
</p>

<p>
  <strong>Period:</strong>
  <%= @score.period %>
</p>

<p>
  <strong>Area:</strong>
  <%= @score.area %>
</p>

<p>
  <strong>Score:</strong>
  <%= @score.score %>
</p>

<p>
  <strong>Student:</strong>
  <%= @score.student %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>