config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :programs
  resources :nutritions do 
    get :export_nutritions
    collection do 
      post :import 
    end
  end
  resources :homes
  resources :attendances
  resources :scores do
    get :export_scores
    collection do
      post :import 
    end
  end
  resources :schools
  resources :establishments do 
    collection { post :import }
  end
  resources :health_cares
  resources :students do 
    get :export
    collection { post :import }
  end
  resources :guardians
  resources :visitors
  devise_for :users
  resources :users
  root :to => 'public#index'
	get '/home', :to => 'homes#banner'
	get '/reports', :to => 'reports#index'
	
end

app/models/program.rb
class Program < ActiveRecord::Base
	has_many :activities
	validates :line, :name, :description, presence: true
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :admin_only, only: [:edit, :update, :new, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.includes(activities: [:students]).all
		@programs_edu = Program.includes(activities: [:students]).where(line: "epc");
		@programs_m = Program.includes(activities: [:students]).where(line: "n");
		@programs_h = Program.includes(activities: [:students]).where(line: "h");
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to new_activity_url, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to programs_url, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.includes(activities: [:students]).find(params[:id])
    end
    
    def admin_only
      unless current_user.admin?
        redirect_to "/", :alert => "Accesso denegado."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:name, :line, :city, :description, :active)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<br /><br />
<div class="row">
	<div class="large-7 columns large-centered">
		<div class="text-center">
			<%= simple_form_for(@program) do |f| %>
			  <h5 class="text-center">Creación de programa</h5>
			  <%= f.error_notification %>
			  <div class="form-inputs">
				<%= f.input :line, label: "Escoge la linea del programa", collection: GeneralInfo.lines, prompt: "Escoger uno" %>
			    <%= f.input :name, label: "Nombre del programa" %>
			    <%= f.input :description, label: "Descripción del programa" %>
			  </div>
	
			  <div class="form-actions">
			    <%= f.button :submit, "Siguiente paso", class: "button success round" %>
			  </div>
			<% end %>
		</div>	
	</div>
</div>

app/views/programs/edit.html.erb
<div class="breadcrumb">
  <h4 class="whitetxt">Editando <%= @program.name %></h4>
</div>
<div class="search-field"></div>
<div class="back_link">
  <%= link_to programs_path do %>
    <%= fa_icon "arrow-left" %> <span class="italic">Regresar</span>
  <% end %>
</div>
<br />	

<%= render 'form' %>

app/views/programs/index.html.erb
<div class="breadcrumb">
  <h4 class="whitetxt">Lista de programas</h4>
</div>
<div class="search-field">
   <br />
   <h5 class="subheader">En esta pantalla podrás asignar programas a cualquier institución o sede inscrita</h5>
</div>
<div class="back_link">
  <%= link_to programs_path do %>
    <%= fa_icon "arrow-left" %> <span class="italic">Regresar</span>
  <% end %>
  <%= link_to 'Nuevo Programa', new_program_path, class: "button success round right" %>
</div>

<ul class="accordion" data-accordion>
  <li class="accordion-navigation">
    <a class="negro italic bold" href="#panel1a"><%= fa_icon "book" %> Educación de Calidad</a>
	<p class="pre-info">La formación en estrategias pedagógicas es una herramienta creada para satisfacer las necesidades de padres o tutores inscritos en el prgrama, en el cual se
enseñaran herramientas útiles del día a día para la generación de ingresos con base en el emprendimiento de bajo impacto.</p>
    <div id="panel1a" class="content active">
		<ul class="accordion activities" data-accordion>
	      <% @programs_edu.each do |program| %>
		  <li class="accordion-navigation ">
			  <a href="#p1"><%= fa_icon "angle-right angle" %><%= program.name %></a><%= link_to edit_program_path(program), class: "edit-right" do %><%= fa_icon "edit" %> <% end %> 
			  <div id="p1" class="content">
				  <% program.activities.each do |activity| %>
					  <ul class="inline-list">
					  	<li><%= link_to activity.name, edit_activity_path(activity) %></li>
						<li>
							<% @cnt = [] %>
							<%# activity.assistances.each do |assistance| %>
								<%# assistance.student.try(:name) %>
								<%# assistance.try(:assistance_mark) %>
							<%# end %>
							<% activity.students.each do |student| %> 
								<% if student.school.present? %>
									<% @cnt.push(student.school.name) unless @cnt.include?(student.school.name)  %>
								<% end %>
							<% end %>
							<%= @cnt.size %> Sedes
						</li>
						<li><%= activity.boss %></li>
						<li><%= activity.students.count %> Estudiantes</li>
					  </ul>
				  <% end %>
			  </div>
		  </li>
		  <% end %>
		 </ul>
		 <%= link_to 'Nueva actividad', new_activity_path, class: "button success round" %>
    </div>
  </li>
  <li class="accordion-navigation">
    <a class="negro italic bold" href="#panel2a"><%= fa_icon "wrench" %> Herramientas para la vida</a>
	<p class="pre-info">El tejido amazónico usado como un medio de generación de ingresos por medio de la manufactura y venta de telares con diseños únicos.</p>
    <div id="panel2a" class="content">
	<ul class="accordion activities" data-accordion>
      <% @programs_h.each do |program| %>
	  <li class="accordion-navigation">
		  <a href="#p1"><%= fa_icon "angle-right angle" %><%= program.name %></a> <%= link_to edit_program_path(program), class: "edit-right" do %><%= fa_icon "edit" %> <% end %>
		  <div id="p1" class="content">
			  <% program.activities.each do |activity| %>
				  <ul class="inline-list">
				  	<li><%= link_to activity.name, edit_activity_path(activity) %></li>
					<li>
						<% @cnt = [] %>
						<% activity.students.each do |student| %> 
							<% if student.school.present? %>
								<% @cnt.push(student.school.name) unless @cnt.include?(student.school.name)  %>
							<% end %>
						<% end %>
						<%= @cnt.size %> Sedes
					</li>
					<li><%= activity.boss %></li>
					<li><%= activity.students.count %> Estudiantes</li>
				  </ul>
			  <% end %>
		  </div>
	  </li>
	  <% end %>
	 </ul>
	 <%= link_to 'Nueva actividad', new_activity_path, class: "button success round" %>
    </div>
  </li>
  <li class="accordion-navigation">
    <a class="negro italic bold" href="#panel3a"><%= fa_icon "cutlery" %> Nutrición</a>
	<p class="pre-info">El tejido amazónico usado como un medio de generación de ingresos por medio de la manufactura y venta de telares con diseños únicos.</p>
    <div id="panel3a" class="content">
	<ul class="accordion activities" data-accordion>
      <% @programs_m.each do |program| %>
	  <li class="accordion-navigation">
		  <a href="#p1"><%= fa_icon "angle-right angle" %><%= program.name %></a> <%= link_to edit_program_path(program), class: "edit-right" do %><%= fa_icon "edit" %> <% end %> 
		  <div id="p1" class="content">
			  <% program.activities.each do |activity| %>
				  <ul class="inline-list">
				  	<li><%= link_to activity.name, edit_activity_path(activity) %></li>
					<li>
						<% @cnt = [] %>
						<% activity.students.each do |student| %> 
							<% if student.school.present? %>
								<% @cnt.push(student.school.name) unless @cnt.include?(student.school.name)  %>
							<% end %>
						<% end %>
						<%= @cnt.size %> Sedes
					</li>
					<li><%= activity.boss %></li>
					<li><%= activity.students.count %> Estudiantes</li>
				  </ul>
			  <% end %>
		  </div>
	  </li>
	  <% end %>
	 </ul>
	 <%= link_to 'Nueva actividad', new_activity_path, class: "button success round" %>
    </div>
  </li>
</ul>

app/views/programs/new.html.erb
<div class="breadcrumb">
  <h4 class="whitetxt">Nuevo programa</h4>
</div>
<div class="search-field">
	<br />
    <h5 class="subheader">En esta pantalla podras crear nuevos programas</h5>
</div>

<%= render 'form' %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @program.name %>
</p>

<p>
  <strong>Line:</strong>
  <%= @program.line %>
</p>

<p>
  <strong>City:</strong>
  <%= @program.city %>
</p>

<p>
  <strong>Description:</strong>
  <%= @program.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @program.active %>
</p>

<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>