config/routes.rb
Rails.application.routes.draw do
  resources :activities
  resources :programs
  resources :nutritions do 
    get :export_nutritions
    collection do 
      post :import 
    end
  end
  resources :homes
  resources :attendances
  resources :scores do
    get :export_scores
    collection do
      post :import 
    end
  end
  resources :schools
  resources :establishments do 
    collection { post :import }
  end
  resources :health_cares
  resources :students do 
    get :export
    collection { post :import }
  end
  resources :guardians
  resources :visitors
  devise_for :users
  resources :users
  root :to => 'public#index'
	get '/home', :to => 'homes#banner'
	get '/reports', :to => 'reports#index'
	
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :program
	has_many :assistances
	has_many :students, through: :assistances
	accepts_nested_attributes_for :assistances
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
		@activity.assistances.build
    @schools = School.includes(:students).order(:name)
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    respond_to do |format|
      if @activity.save
        format.html { redirect_to programs_url, notice: 'La actividad ha sido creada.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
		am = params[:activity][:assistances_attributes]
    respond_to do |format|
      if @activity.update(activity_params)
				@old_ones = Assistance.where(id: @activity.assistance_ids).update_all(assistance_mark: false)
				@assistances = Assistance.where(id: am).update_all(assistance_mark: true)
        format.html { redirect_to programs_url, notice: 'La actividad ha sido actualizada.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :the_date, :boss, :active, :description, :program_id, {student_ids: []}, assistances_attributes: [:assistance_mark, :id])
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<br/><br/>
<div class="text-center">
  <%= simple_form_for(@activity) do |f| %>
      <h5 class="text-center">Creación de actividades</h5>
      <%= f.error_notification %>
      <div class="form-inputs">
        <%= f.association :program, label: "Escoge el programa asociado" %>
        <div class="row">
          <div class="large-8 columns large-centered">
            <%= f.input :name, label: "Nombre de la actividad" %>
            <div class="inline-select center">
              <%= f.input :the_date, label: "Fecha de la actividad" %>
            </div>
            <br/>
            <%= f.input :boss, label: "Persona a cargo" %>
            <%= f.input :description, label: "Descripción de la actividad" %>
          </div>
        </div>
        <h5 class="text-center">Asigna sedes cursos y estudiantes a esta actividad.</h5>
        <%# f.association :students, label: "Escoge estudiantes" %>
        <br/>
        <% if @activity.students.count > 0 %>
            <h6><%= @activity.students.count %> estudiantes seleccionados</h6>
        <% end %>
        <ul class="accordion" data-accordion>
          <%= fa_icon "angle-right angle none" %>
          <% @schools.each do |school| %>
              <li class="accordion-navigation">
                <a href="#student-<%= school.id %>"><%= school.name %></a>
                <div id="student-<%= school.id %>" class="students content">
                  <div class="grados">
                    <input type="search" name="student_search" class="student_search" placeholder="buscar estudiante"/>
                    <a href="#" class="label round" data-course="0">Todos</a>
                    <a href="#" class="label round" data-course="1">1er</a>
                    <a href="#" class="label round" data-course="2">2do</a>
                    <a href="#" class="label round" data-course="3">3er</a><a href="#" class="label round" data-course="4">4to</a><a href="#" class="label round" data-course="5">5to</a><a href="#" class="label round" data-course="6">6to</a><a href="#" class="label round" data-course="7">7mo</a><a href="#" class="label round" data-course="8">8vo</a><a href="#" class="label round" data-course="9">9no</a><a href="#" class="label round" data-course="10">10</a><a href="#" class="label round" data-course="11">11</a>
                  </div>
                  <% school.students.order(:last_course).find_each do |student| %>
                      <label class="text-left course-<%= student.last_course %>">
                        <%= check_box_tag "activity[student_ids][]", student.id, @activity.students.include?(student) %>
                        <div class="student-info ib">
                          <h6 class="student_name"><%= student.name %></h6>
                          <h6 class="subheader">
                            <i><%= student.school.name %></i>
                          </h6>
                          <h6 class="subheader"><%= fa_icon "map-marker" %> <%= student.residency_state %></h6>
                        </div>
                        <div class="student-info iden ib">
                          <h6 class="text-center">Tarjeta de identidad</h6>
                          <h6 class="subheader text-center"><%= student.identification %></h6>
                        </div>
                        <div class="student-info edad ib">
                          <h6 class="text-center">Edad</h6>
                          <h6 class="subheader text-center"><%= student.identification %></h6>
                        </div>
                        <div class="student-info edad ib">
                          <h6 class="text-center">Edad</h6>
                          <h6 class="subheader text-center"><%= student.age %></h6>
                        </div>
                        <div class="student-info grado ib">
                          <h6 class="text-center">grado</h6>
                          <h6 class="subheader text-center"><%= student.last_course %></h6>
                        </div>
                        <div class="right assistance">
                          <h6 class="text-center">Asistio?</h6>
                          <% if @activity.id.present? %>
                              <% @court = Assistance.where(activity_id: @activity.id).where(student_id: student.id).first %>
                          <% else %>
                              <% @court = nil %>
                          <% end %>
                          <%= check_box_tag "activity[assistances_attributes][]", @court.try(:id), @court.try(:assistance_mark) %>
                        </div>
                      </label>
                  <% end %>
                </div>
              </li>
          <% end %>
        </ul>
        <br/><br/>
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Siguiente paso", class: "button success round" %>
      </div>
  <% end %>
</div>

app/views/activities/edit.html.erb
<div class="breadcrumb">
  <h4 class="whitetxt">Editar actividad</h4>
</div>
<div class="search-field">
	<br />
    <h5 class="subheader">En esta pantalla podras editar actividades y asociarlas con estudiantes</h5>
</div>
<div class="back_link">
  <%= link_to programs_path do %>
    <%= fa_icon "arrow-left" %> <span class="italic">Regresar</span>
  <% end %>
</div>


<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Activities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>The date</th>
      <th>Boss</th>
      <th>Active</th>
      <th>Program</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.name %></td>
        <td><%= activity.the_date %></td>
        <td><%= activity.boss %></td>
        <td><%= activity.active %></td>
        <td><%= activity.program %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<div class="breadcrumb">
  <h4 class="whitetxt">Nueva actividad</h4>
</div>
<div class="search-field">
	<br />
    <h5 class="subheader">En esta pantalla podras crear nuevas actividades e inscribiarlas a programas</h5>
</div>

<%= render 'form' %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>The date:</strong>
  <%= @activity.the_date %>
</p>

<p>
  <strong>Boss:</strong>
  <%= @activity.boss %>
</p>

<p>
  <strong>Active:</strong>
  <%= @activity.active %>
</p>

<p>
  <strong>Program:</strong>
  <%= @activity.program %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>